---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "bank-api-s3proxy-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "bank-api-s3proxy"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  AZURE_TENANT_ID: "{{ .Values.secrets.bank_api_s3proxy.AZURE_TENANT_ID }}"
  AZURE_CLIENT_ID: "{{ .Values.secrets.bank_api_s3proxy.AZURE_CLIENT_ID }}"
  AZURE_CLIENT_SECRET: "{{ .Values.secrets.bank_api_s3proxy.AZURE_CLIENT_SECRET }}"
type: "Opaque"
