---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "bank-api-s3proxy-service"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "bank-api-s3proxy"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "bank-api-s3proxy"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
  ports:
    - name: "http"
      protocol: "TCP"
      port: 6070
      targetPort: 6070
