---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "bank-api-mcp-deployment"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "bank-api-mcp"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Chart.Name }}"
        app.kubernetes.io/component: "bank-api-mcp"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
        - image: "{{ .Values.parameters.bank_api_mcp.bank_api_mcp_image }}"
          name: "bank-api-mcp"
          envFrom:
            - configMapRef:
                name: "bank-api-mcp-config"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: {{ .Values.parameters.bank_api_mcp.port_http | int }}
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Chart.Name }}"
      app.kubernetes.io/component: "bank-api-mcp"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
