---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "bank-api-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "bank-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.bank_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.bank_api.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.parameters.bank_api.port_http | int | toString }}"
  BANK_API_POSTGRES_HOST: "{{ .Values.config.bank_api.BANK_API_POSTGRES_HOST }}"
  BANK_API_POSTGRES_PORT: "{{ .Values.config.bank_api.BANK_API_POSTGRES_PORT }}"
  BANK_API_POSTGRES_USERNAME: "{{ .Values.config.bank_api.BANK_API_POSTGRES_USERNAME }}"
  BANK_API_POSTGRES_JDBCCONNECTIONSTRING: "{{ .Values.config.bank_api.BANK_API_POSTGRES_JDBCCONNECTIONSTRING }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.config.bank_api.OTEL_EXPORTER_OTLP_ENDPOINT }}"
  OTEL_EXPORTER_OTLP_PROTOCOL: "{{ .Values.config.bank_api.OTEL_EXPORTER_OTLP_PROTOCOL }}"
  OTEL_SERVICE_NAME: "{{ .Values.config.bank_api.OTEL_SERVICE_NAME }}"
