---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "bank-api-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "bank-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__bank-api-postgres: "Host=bank-api-postgres-service;Port=5432;Username=postgres;Password={{ .Values.secrets.bank_api.bank_api_postgres_password }}"
  BANK_API_POSTGRES_PASSWORD: "{{ .Values.secrets.bank_api.bank_api_postgres_password }}"
  BANK_API_POSTGRES_URI: "postgresql://postgres:{{ .Values.secrets.bank_api.bank_api_postgres_password }}@bank-api-postgres-service:5432"
type: "Opaque"
