---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "bank-api-dapr-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "bank-api-dapr"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ASPNETCORE_ENVIRONMENT: "{{ .Values.secrets.bank_api_dapr.ASPNETCORE_ENVIRONMENT }}"
  AZURE_TENANT_ID: "{{ .Values.secrets.bank_api_dapr.AZURE_TENANT_ID }}"
  AZURE_CLIENT_ID: "{{ .Values.secrets.bank_api_dapr.AZURE_CLIENT_ID }}"
  AZURE_CLIENT_SECRET: "{{ .Values.secrets.bank_api_dapr.AZURE_CLIENT_SECRET }}"
type: "Opaque"
