@hostname = localhost
@port = 5200
@host = {{hostname}}:{{port}}
@localToken = test

###

http://{{host}}/.well-known/oauth-protected-resource

###

http://{{host}}
Accept: text/event-stream
Authorization: Bearer {{localToken}}

###