// <auto-generated/>
#pragma warning disable CS0618
using DownstreamClients.GitHub.Repos.Item.Item.Releases.GenerateNotes;
using DownstreamClients.GitHub.Repos.Item.Item.Releases.Item;
using DownstreamClients.GitHub.Repos.Item.Item.Releases.Latest;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DownstreamClients.GitHub.Repos.Item.Item.Releases
{
    /// <summary>
    /// Builds and executes requests for operations under \repos\{owner}\{repo}\releases
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReleasesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The generateNotes property</summary>
        public global::DownstreamClients.GitHub.Repos.Item.Item.Releases.GenerateNotes.GenerateNotesRequestBuilder GenerateNotes
        {
            get => new global::DownstreamClients.GitHub.Repos.Item.Item.Releases.GenerateNotes.GenerateNotesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The latest property</summary>
        public global::DownstreamClients.GitHub.Repos.Item.Item.Releases.Latest.LatestRequestBuilder Latest
        {
            get => new global::DownstreamClients.GitHub.Repos.Item.Item.Releases.Latest.LatestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the DownstreamClients.GitHub.repos.item.item.releases.item collection</summary>
        /// <param name="position">The unique identifier of the release.</param>
        /// <returns>A <see cref="global::DownstreamClients.GitHub.Repos.Item.Item.Releases.Item.WithRelease_ItemRequestBuilder"/></returns>
        public global::DownstreamClients.GitHub.Repos.Item.Item.Releases.Item.WithRelease_ItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("release_id", position);
                return new global::DownstreamClients.GitHub.Repos.Item.Item.Releases.Item.WithRelease_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the DownstreamClients.GitHub.repos.item.item.releases.item collection</summary>
        /// <param name="position">The unique identifier of the release.</param>
        /// <returns>A <see cref="global::DownstreamClients.GitHub.Repos.Item.Item.Releases.Item.WithRelease_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::DownstreamClients.GitHub.Repos.Item.Item.Releases.Item.WithRelease_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("release_id", position);
                return new global::DownstreamClients.GitHub.Repos.Item.Item.Releases.Item.WithRelease_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DownstreamClients.GitHub.Repos.Item.Item.Releases.ReleasesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReleasesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner}/{repo}/releases", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DownstreamClients.GitHub.Repos.Item.Item.Releases.ReleasesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReleasesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/repos/{owner}/{repo}/releases", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
