---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "bank-api-db-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "bank-api-db"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  POSTGRES_PASSWORD: "{{ .Values.secrets.bank_api_db.bank_api_db_password }}"
type: "Opaque"
