apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: bank-api
spec:
  schema:
    apiVersion: v1alpha1
    kind: BankApi
    spec:
      name: string | default="bank-api"
      namespace: string | default="infra-services"
      replicas: integer | default=1
      envSecretName: string | default="bank-api-env"
      gateway:
        enabled: boolean | default=false
        gatewayName: string | default="eg"
        gatewayNamespace: string | default="infra-services"
        host: string
        path: string | default="/"
    status:
      availableReplicas: ${deployment.status.availableReplicas}

  resources:
    - id: targetNamespace
      template:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: ${schema.spec.namespace}

    - id: serviceAccount
      template:
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: ${schema.spec.name}
          namespace: ${schema.spec.namespace}

    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.spec.name}
          namespace: ${schema.spec.namespace}
          labels:
            app.kubernetes.io/name: ${schema.spec.name}
            app.kubernetes.io/instance: ${schema.spec.name}
        spec:
          replicas: ${schema.spec.replicas}
          selector:
            matchLabels:
              app.kubernetes.io/name: ${schema.spec.name}
          template:
            metadata:
              labels:
                app.kubernetes.io/name: ${schema.spec.name}
            spec:
              resources:
                requests:
                  cpu: "100m"
                  memory: "512Mi"
                limits:
                  cpu: "500m"
                  memory: "2Gi"
              serviceAccountName: ${serviceAccount.metadata.name}
              automountServiceAccountToken: false

              volumes:
                - name: serviceaccount-token
                  projected:
                    sources:
                      - serviceAccountToken:
                          path: token
                          audience: http://localhost:8080/realms/bank # Keycloak audience
                          expirationSeconds: 3600

              # 'restartPolicy: Always' on initContainers makes it a sidecar, please see:
              # https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/#sidecar-example
              initContainers:
                - name: otelcol
                  image: ghcr.io/erwinkramer/bank-api-otelcol:latest
                  restartPolicy: Always
                  envFrom:
                    - secretRef:
                        name: ${schema.spec.envSecretName}

                - name: proxy
                  image: ghcr.io/erwinkramer/bank-api-proxy:latest
                  restartPolicy: Always
                  ports:
                    - containerPort: 10000
                      name: http-proxy

                - name: dapr
                  image: ghcr.io/erwinkramer/bank-api-dapr:latest
                  restartPolicy: Always
                  ports:
                    - containerPort: 3500
                      name: dapr-http
                  envFrom:
                    - secretRef:
                        name: ${schema.spec.envSecretName}

                - name: s3proxy
                  image: ghcr.io/erwinkramer/bank-api-s3proxy:latest
                  restartPolicy: Always
                  ports:
                    - containerPort: 6070
                      name: s3proxy
                  envFrom:
                    - secretRef:
                        name: ${schema.spec.envSecretName}

              # The main application container
              containers:
                - name: api-stable
                  image: ghcr.io/erwinkramer/bank-api:latest
                  ports:
                    - containerPort: 8080
                      name: http-api-stable
                  env:
                    - name: ApiDocument__Servers__0__Url
                      value: https://${schema.spec.gateway.host}/v1
                    - name: ApiDocument__Servers__1__Url
                      value: http://localhost:5201/v1
                  envFrom:
                    - secretRef:
                        name: ${schema.spec.envSecretName}
                  volumeMounts:
                    - name: serviceaccount-token
                      mountPath: /var/run/secrets/${schema.spec.name}
                      readOnly: true
                  readinessProbe:
                    httpGet:
                      path: /.well-known/jwks.json
                      port: http-api-stable
                    initialDelaySeconds: 3
                    periodSeconds: 5
                - name: api-beta
                  image: ghcr.io/erwinkramer/bank-api:nightly
                  ports:
                    - containerPort: 8081
                      name: http-api-beta
                  env:
                    - name: ASPNETCORE_HTTP_PORTS
                      value: "8081"
                    - name: ApiDocument__Servers__0__Url
                      value: https://${schema.spec.gateway.host}/v2
                    - name: ApiDocument__Servers__1__Url
                      value: http://localhost:5201/v2
                  envFrom:
                    - secretRef:
                        name: ${schema.spec.envSecretName}
                  volumeMounts:
                    - name: serviceaccount-token
                      mountPath: /var/run/secrets/${schema.spec.name}
                      readOnly: true
                  readinessProbe:
                    httpGet:
                      path: /.well-known/jwks.json
                      port: http-api-beta
                    initialDelaySeconds: 3
                    periodSeconds: 5
    - id: service
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: ${schema.spec.name}
          namespace: ${schema.spec.namespace}
        spec:
          type: ClusterIP
          selector:
            app.kubernetes.io/name: ${schema.spec.name}
          ports:
            - name: http
              port: 80
              targetPort: http-proxy
            - name: api-stable
              port: 8080
              targetPort: http-api-stable
            - name: api-beta
              port: 8081
              targetPort: http-api-beta
            - name: dapr
              port: 3500
              targetPort: dapr-http
            - name: s3proxy
              port: 6070
              targetPort: s3proxy

    - id: httproute
      includeWhen:
        - ${schema.spec.gateway.enabled}
      template:
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: ${schema.spec.name}
          namespace: ${schema.spec.namespace}
        spec:
          parentRefs:
            - name: ${schema.spec.gateway.gatewayName}
              namespace: ${schema.spec.gateway.gatewayNamespace}
          hostnames:
            - ${schema.spec.gateway.host}
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: ${schema.spec.gateway.path}
              backendRefs:
                - name: ${service.metadata.name}
                  port: 80
