apiVersion: kro.run/v1alpha1
kind: BankApi
metadata:
  name: bank-api
spec:
  replicas: 1
  envSecretName: bank-api-env
  gateway:
    enabled: true
    hosts:
      - "bankapi.w.guanchen.nl"
    path: /
