apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: bank-api
spec:
  schema:
    apiVersion: v1alpha1
    kind: BankApi
    spec:
      name: string | default="bank-api"
      namespace: string | default="infra-services"
      replicas: integer | default=1
      envSecretName: string | default="bank-api-env"
      gateway:
        enabled: boolean | default=false
        gatewayName: string | default="eg"
        gatewayNamespace: string | default="infra-services"
        hosts: "[]string"
        path: string | default="/"
    status:
      availableReplicas: ${deployment.status.availableReplicas}

  resources:
    - id: targetNamespace
      template:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: ${schema.spec.namespace}

    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.spec.name}
          namespace: ${schema.spec.namespace}
          labels:
            app.kubernetes.io/name: ${schema.spec.name}
            app.kubernetes.io/instance: ${schema.spec.name}
        spec:
          replicas: ${schema.spec.replicas}
          selector:
            matchLabels:
              app.kubernetes.io/name: ${schema.spec.name}
          template:
            metadata:
              labels:
                app.kubernetes.io/name: ${schema.spec.name}
            spec:
              # 'restartPolicy: Always' on initContainers makes it a sidecar, please see:
              # https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/#sidecar-example
              initContainers:
                - name: otelcol
                  image: ghcr.io/erwinkramer/bank-api-otelcol:latest
                  restartPolicy: Always
                  envFrom:
                    - secretRef:
                        name: ${schema.spec.envSecretName}

                - name: proxy
                  image: ghcr.io/erwinkramer/bank-api-proxy:latest
                  restartPolicy: Always
                  ports:
                    - containerPort: 10000
                      name: http-proxy

                - name: dapr
                  image: ghcr.io/erwinkramer/bank-api-dapr:latest
                  restartPolicy: Always
                  ports:
                    - containerPort: 3500
                      name: dapr-http
                  envFrom:
                    - secretRef:
                        name: ${schema.spec.envSecretName}

                - name: s3proxy
                  image: ghcr.io/erwinkramer/bank-api-s3proxy:latest
                  restartPolicy: Always
                  ports:
                    - containerPort: 6070
                      name: s3proxy
                  envFrom:
                    - secretRef:
                        name: ${schema.spec.envSecretName}

              # The main application container
              containers:
                - name: api
                  image: ghcr.io/erwinkramer/bank-api:latest
                  ports:
                    - containerPort: 8080
                      name: http-api
                  envFrom:
                    - secretRef:
                        name: ${schema.spec.envSecretName}
                  readinessProbe:
                    httpGet:
                      path: /.well-known/jwks.json
                      port: http-api
                    initialDelaySeconds: 3
                    periodSeconds: 5
    - id: service
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: ${schema.spec.name}
          namespace: ${schema.spec.namespace}
        spec:
          type: ClusterIP
          selector:
            app.kubernetes.io/name: ${schema.spec.name}
          ports:
            - name: http
              port: 80
              targetPort: http-proxy
            - name: api
              port: 8080
              targetPort: http-api
            - name: dapr
              port: 3500
              targetPort: dapr-http
            - name: s3proxy
              port: 6070
              targetPort: s3proxy

    - id: httproute
      includeWhen:
        - ${schema.spec.gateway.enabled}
      template:
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: ${schema.spec.name}
          namespace: ${schema.spec.namespace}
        spec:
          parentRefs:
            - name: ${schema.spec.gateway.gatewayName}
              namespace: ${schema.spec.gateway.gatewayNamespace}
          hostnames: ${schema.spec.gateway.hosts}
          rules:
            - matches:
                - path:
                    type: PathPrefix
                    value: ${schema.spec.gateway.path}
              backendRefs:
                - name: ${service.metadata.name}
                  port: 80
