parameters:
  bank_api_s3proxy:
    bank_api_s3proxy_image: "bank-api-s3proxy:latest"
  bank_api_dapr:
    bank_api_dapr_image: "bank-api-dapr:latest"
  bank_api:
    port_http: 8080
    bank_api_image: "bank-api:latest"
  bank_api_beta:
    port_http: 8080
    bank_api_beta_image: "bank-api-beta:latest"
  bank_api_mcp:
    port_http: 8080
    bank_api_mcp_image: "bank-api-mcp:latest"
secrets:
  bank_api_db:
    bank_api_db_password: ""
  bank_api_s3proxy:
    ASPNETCORE_ENVIRONMENT: ""
    AZURE_TENANT_ID: ""
    AZURE_CLIENT_ID: ""
    AZURE_CLIENT_SECRET: ""
  bank_api_dapr:
    ASPNETCORE_ENVIRONMENT: ""
    AZURE_TENANT_ID: ""
    AZURE_CLIENT_ID: ""
    AZURE_CLIENT_SECRET: ""
  bank_api:
    ConnectionStrings__bank_api_db: ""
    bank_api_db_password: ""
    BANK_API_DB_URI: ""
  bank_api_beta:
    ConnectionStrings__bank_api_db: ""
    bank_api_db_password: ""
    BANK_API_DB_URI: ""
config:
  bank_api_db:
    POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    POSTGRES_USER: "postgres"
  bank_api:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    HTTP_PORTS: ""
    BANK_API_DB_HOST: "bank-api-db-service"
    BANK_API_DB_PORT: "5432"
    BANK_API_DB_USERNAME: "postgres"
    BANK_API_DB_JDBCCONNECTIONSTRING: "jdbc:postgresql://bank-api-db-service:5432"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://k8s-dashboard-service:18889"
    OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
    OTEL_SERVICE_NAME: "bank-api"
  bank_api_beta:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    HTTP_PORTS: ""
    BANK_API_DB_HOST: "bank-api-db-service"
    BANK_API_DB_PORT: "5432"
    BANK_API_DB_USERNAME: "postgres"
    BANK_API_DB_JDBCCONNECTIONSTRING: "jdbc:postgresql://bank-api-db-service:5432"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://k8s-dashboard-service:18889"
    OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
    OTEL_SERVICE_NAME: "bank-api-beta"
  bank_api_mcp:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    HTTP_PORTS: ""
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://k8s-dashboard-service:18889"
    OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
    OTEL_SERVICE_NAME: "bank-api-mcp"
