apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore-bankapi
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
    - name: vaultName
      value: kv-certificates-01123
    - name: azureTenantId
      secretKeyRef:
        name: AZURE_TENANT_ID
        key: AZURE_TENANT_ID
    - name: azureClientId
      secretKeyRef:
        name: AZURE_CLIENT_ID
        key: AZURE_CLIENT_ID
    - name: azureClientSecret
      secretKeyRef:
        name: AZURE_CLIENT_SECRET
        key: AZURE_CLIENT_SECRET
auth:
  secretStore: envvar-secret-store