---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "bank-api-beta-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "bank-api-beta"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__bank-api-db: "Host=bank-api-db-service;Port=5432;Username=postgres;Password={{ .Values.secrets.bank_api_beta.bank_api_db_password }}"
  BANK_API_DB_PASSWORD: "{{ .Values.secrets.bank_api_beta.bank_api_db_password }}"
  BANK_API_DB_URI: "postgresql://postgres:{{ .Values.secrets.bank_api_beta.bank_api_db_password }}@bank-api-db-service:5432"
type: "Opaque"
