---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "bank-api-postgres-statefulset"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "bank-api-postgres"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Chart.Name }}"
        app.kubernetes.io/component: "bank-api-postgres"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
        - image: "docker.io/postgres:18-alpine"
          name: "bank-api-postgres"
          envFrom:
            - configMapRef:
                name: "bank-api-postgres-config"
            - secretRef:
                name: "bank-api-postgres-secrets"
          ports:
            - name: "tcp"
              protocol: "TCP"
              containerPort: 5432
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Chart.Name }}"
      app.kubernetes.io/component: "bank-api-postgres"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  replicas: 1
  persistentVolumeClaimRetentionPolicy: {}
  updateStrategy:
    rollingUpdate: {}
    type: "RollingUpdate"
