name: Create ACA revision

on:
  workflow_run:
    workflows:
      - Build and push API as container
    types:
      - completed

env:
  AZURE_CORE_OUTPUT: none
  RESOURCE_GROUP: containering
  APP_NAME: app

jobs:
  create-revision:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Login to Azure
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_84A42EE1996547A7A0A282482CA49AB4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D81009FFC4CE496AA7E4E814522B98BE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_878C3EB021014E2EA7909DDF503EB8D4 }}

      - name: Create Container App revision
        uses: azure/cli@v3
        with:
          inlineScript: |
            az containerapp revision copy \
              --resource-group "${{ env.RESOURCE_GROUP }}" \
              --name "${{ env.APP_NAME }}" \
              --revision-suffix "gha-${{ github.run_id }}-${{ github.run_attempt }}"
