name: Create ACA revision

on:
  workflow_run:
    workflows:
      - Build and push API as container
    types:
      - completed

env:
  AZURE_CORE_OUTPUT: none
  RESOURCE_GROUP: containering

jobs:
  create-revision:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Login to Azure
        uses: azure/login@v3
        with:
          client-id: ${{ vars.APP_AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.APP_AZURE_TENANT_ID }}
          subscription-id: ${{ vars.APP_AZURE_SUBSCRIPTION_ID }}
      - uses: actions/checkout@v7
      - name: Deploy Bicep
        uses: azure/cli@v3
        with:
          inlineScript: |
            deployment_name="bank-api-${{ github.run_id }}-${{ github.run_attempt }}"

            az deployment group create \
              --subscription "${{ vars.APP_AZURE_SUBSCRIPTION_ID }}" \
              --resource-group "${{ env.RESOURCE_GROUP }}" \
              --name "$deployment_name" \
              --template-file Infra.Bicep/main.bicep
