name: Build and push API as container

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: ghcr.io/${{ github.repository }}:latest
            context: .
          - image: ghcr.io/${{ github.repository }}:nightly
            context: .
            args: --build-arg SERVICENAME=BankApi.Service.Beta
          - image: ghcr.io/${{ github.repository }}-mcp:latest
            context: .
            args: --build-arg SERVICENAME=BankApi.Mcp
          - image: ghcr.io/${{ github.repository }}-dapr:latest
            context: ./Sidecar.Dapr
          - image: ghcr.io/${{ github.repository }}-proxy:latest
            context: ./Sidecar.Proxy
          - image: ghcr.io/${{ github.repository }}-s3proxy:latest
            context: ./Sidecar.S3Proxy
          - image: ghcr.io/${{ github.repository }}-otelcol:latest
            context: ./Sidecar.OpenTelemetry
    steps:
      - uses: actions/checkout@v7
      - name: Login and push with Podman
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
            podman login ghcr.io \
              --username ${{ github.actor }} \
              --password-stdin
          podman build ${{ matrix.args}} -t ${{ matrix.image }} ${{ matrix.context }}
          podman push ${{ matrix.image }}
