name: Build and push API as container

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Login and push with Podman
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
            podman login ghcr.io \
              --username ${{ github.actor }} \
              --password-stdin
          podman build -t ghcr.io/${{ github.repository }}:latest .
          podman push ghcr.io/${{ github.repository }}:latest
